knp_snappy:
    pdf:
        enabled:    true
        binary:     "\"D:\\programs\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
        options:    []
    image:
        enabled:    true
        binary:     "\"D:\\programs\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
        options:    []
